### ISSUE TITLE
TwitchManager Auth

### ISSUE THREAD

**Issue by iProdigy** [Dyskal/TwitchPlayerOpener#15]
Hi!

You should avoid sharing your app access token publicly (treat it as confidentially as a password). Instead it's best to read this from an environmental variable or a file that is not shared to git. Here's how you can revoke the token that was shared: https://dev.twitch.tv/docs/authentication#revoking-access-tokens

**Comment by Dyskal** [comment]
Hi, 
I had not seen on the website that the app access token should be private, but i will revoke it.
Do you have an idea to automate the app access token to avoid creating a new release every +/- 60 days ?

**Comment by iProdigy** [comment]
If you provide a valid client id & secret pair to TwitchClientBuilder, it will automatically create an app access token upon the first api request. The only problem is you need to keep your client secret confidential (i.e. not in a release)

So, you can either require users input their own client id & secret for the application to use or you could switch to kraken (which is deprecated but doesn't require authentication) or you could host a webserver to perform the helix calls on behalf of the individual clients

**Comment by Dyskal** [comment]
thanks a lot for your help, now fixed in v2.4
